[package]
name = "picobot"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
async-openai = { version = "0.32.4", features = ["_api", "byot", "rustls", "chat-completion", "chat-completion-types"] }
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
toml = "0.9"
tokio = { version = "1", features = ["full"] }
